---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jade-shooter
  labels:
    app: jade-shooter
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jade-shooter
  template:
    metadata:
      labels:
        app: jade-shooter
    spec:
      containers:
      - name: jade-shooter0
        image: jwsy/jade-shooter:v1.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: jade-shooter-service
  namespace: default
spec:
  selector:
    app: jade-shooter
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jade-shooter
  labels:
    name: jade-shooter
spec:
  rules:
  - host: shooter.ksingh.localhost
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: jade-shooter-service
            port:
              number: 80
  tls:
  - hosts:
    - shooter.ksingh.localhost
